// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 05 Apr 2024 15:41:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bass

/*
#include "../include/bass.h"
#include "../include/bassenc.h"
#include "../include/bassenc_mp3.h"
#include "../include/bassenc_flac.h"
#include "../include/bassenc_ogg.h"
#include "../include/bassmix.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
// BassH as defined in include/bass.h:9

// Bassversion as defined in include/bass.h:47
Bassversion = 0x204
// Bassversiontext as defined in include/bass.h:48
Bassversiontext = "2.4"
// BassOk as defined in include/bass.h:67
BassOk = 0
// BassErrorMem as defined in include/bass.h:68
BassErrorMem = 1
// BassErrorFileopen as defined in include/bass.h:69
BassErrorFileopen = 2
// BassErrorDriver as defined in include/bass.h:70
BassErrorDriver = 3
// BassErrorBuflost as defined in include/bass.h:71
BassErrorBuflost = 4
// BassErrorHandle as defined in include/bass.h:72
BassErrorHandle = 5
// BassErrorFormat as defined in include/bass.h:73
BassErrorFormat = 6
// BassErrorPosition as defined in include/bass.h:74
BassErrorPosition = 7
// BassErrorInit as defined in include/bass.h:75
BassErrorInit = 8
// BassErrorStart as defined in include/bass.h:76
BassErrorStart = 9
// BassErrorSsl as defined in include/bass.h:77
BassErrorSsl = 10
// BassErrorReinit as defined in include/bass.h:78
BassErrorReinit = 11
// BassErrorAlready as defined in include/bass.h:79
BassErrorAlready = 14
// BassErrorNotaudio as defined in include/bass.h:80
BassErrorNotaudio = 17
// BassErrorNochan as defined in include/bass.h:81
BassErrorNochan = 18
// BassErrorIlltype as defined in include/bass.h:82
BassErrorIlltype = 19
// BassErrorIllparam as defined in include/bass.h:83
BassErrorIllparam = 20
// BassErrorNo3d as defined in include/bass.h:84
BassErrorNo3d = 21
// BassErrorNoeax as defined in include/bass.h:85
BassErrorNoeax = 22
// BassErrorDevice as defined in include/bass.h:86
BassErrorDevice = 23
// BassErrorNoplay as defined in include/bass.h:87
BassErrorNoplay = 24
// BassErrorFreq as defined in include/bass.h:88
BassErrorFreq = 25
// BassErrorNotfile as defined in include/bass.h:89
BassErrorNotfile = 27
// BassErrorNohw as defined in include/bass.h:90
BassErrorNohw = 29
// BassErrorEmpty as defined in include/bass.h:91
BassErrorEmpty = 31
// BassErrorNonet as defined in include/bass.h:92
BassErrorNonet = 32
// BassErrorCreate as defined in include/bass.h:93
BassErrorCreate = 33
// BassErrorNofx as defined in include/bass.h:94
BassErrorNofx = 34
// BassErrorNotavail as defined in include/bass.h:95
BassErrorNotavail = 37
// BassErrorDecode as defined in include/bass.h:96
BassErrorDecode = 38
// BassErrorDx as defined in include/bass.h:97
BassErrorDx = 39
// BassErrorTimeout as defined in include/bass.h:98
BassErrorTimeout = 40
// BassErrorFileform as defined in include/bass.h:99
BassErrorFileform = 41
// BassErrorSpeaker as defined in include/bass.h:100
BassErrorSpeaker = 42
// BassErrorVersion as defined in include/bass.h:101
BassErrorVersion = 43
// BassErrorCodec as defined in include/bass.h:102
BassErrorCodec = 44
// BassErrorEnded as defined in include/bass.h:103
BassErrorEnded = 45
// BassErrorBusy as defined in include/bass.h:104
BassErrorBusy = 46
// BassErrorUnstreamable as defined in include/bass.h:105
BassErrorUnstreamable = 47
// BassErrorProtocol as defined in include/bass.h:106
BassErrorProtocol = 48
// BassErrorDenied as defined in include/bass.h:107
BassErrorDenied = 49
// BassErrorUnknown as defined in include/bass.h:108
BassErrorUnknown = - 1
// BassConfigBuffer as defined in include/bass.h:111
BassConfigBuffer = 0
// BassConfigUpdateperiod as defined in include/bass.h:112
BassConfigUpdateperiod = 1
// BassConfigGvolSample as defined in include/bass.h:113
BassConfigGvolSample = 4
// BassConfigGvolStream as defined in include/bass.h:114
BassConfigGvolStream = 5
// BassConfigGvolMusic as defined in include/bass.h:115
BassConfigGvolMusic = 6
// BassConfigCurveVol as defined in include/bass.h:116
BassConfigCurveVol = 7
// BassConfigCurvePan as defined in include/bass.h:117
BassConfigCurvePan = 8
// BassConfigFloatdsp as defined in include/bass.h:118
BassConfigFloatdsp = 9
// BassConfig3dalgorithm as defined in include/bass.h:119
BassConfig3dalgorithm = 10
// BassConfigNetTimeout as defined in include/bass.h:120
BassConfigNetTimeout = 11
// BassConfigNetBuffer as defined in include/bass.h:121
BassConfigNetBuffer = 12
// BassConfigPauseNoplay as defined in include/bass.h:122
BassConfigPauseNoplay = 13
// BassConfigNetPrebuf as defined in include/bass.h:123
BassConfigNetPrebuf = 15
// BassConfigNetPassive as defined in include/bass.h:124
BassConfigNetPassive = 18
// BassConfigRecBuffer as defined in include/bass.h:125
BassConfigRecBuffer = 19
// BassConfigNetPlaylist as defined in include/bass.h:126
BassConfigNetPlaylist = 21
// BassConfigMusicVirtual as defined in include/bass.h:127
BassConfigMusicVirtual = 22
// BassConfigVerify as defined in include/bass.h:128
BassConfigVerify = 23
// BassConfigUpdatethreads as defined in include/bass.h:129
BassConfigUpdatethreads = 24
// BassConfigDevBuffer as defined in include/bass.h:130
BassConfigDevBuffer = 27
// BassConfigRecLoopback as defined in include/bass.h:131
BassConfigRecLoopback = 28
// BassConfigVistaTruepos as defined in include/bass.h:132
BassConfigVistaTruepos = 30
// BassConfigIosSession as defined in include/bass.h:133
BassConfigIosSession = 34
// BassConfigIosMixaudio as defined in include/bass.h:134
BassConfigIosMixaudio = 34
// BassConfigDevDefault as defined in include/bass.h:135
BassConfigDevDefault = 36
// BassConfigNetReadtimeout as defined in include/bass.h:136
BassConfigNetReadtimeout = 37
// BassConfigVistaSpeakers as defined in include/bass.h:137
BassConfigVistaSpeakers = 38
// BassConfigIosSpeaker as defined in include/bass.h:138
BassConfigIosSpeaker = 39
// BassConfigMfDisable as defined in include/bass.h:139
BassConfigMfDisable = 40
// BassConfigHandles as defined in include/bass.h:140
BassConfigHandles = 41
// BassConfigUnicode as defined in include/bass.h:141
BassConfigUnicode = 42
// BassConfigSrc as defined in include/bass.h:142
BassConfigSrc = 43
// BassConfigSrcSample as defined in include/bass.h:143
BassConfigSrcSample = 44
// BassConfigAsyncfileBuffer as defined in include/bass.h:144
BassConfigAsyncfileBuffer = 45
// BassConfigOggPrescan as defined in include/bass.h:145
BassConfigOggPrescan = 47
// BassConfigMfVideo as defined in include/bass.h:146
BassConfigMfVideo = 48
// BassConfigAirplay as defined in include/bass.h:147
BassConfigAirplay = 49
// BassConfigDevNonstop as defined in include/bass.h:148
BassConfigDevNonstop = 50
// BassConfigIosNocategory as defined in include/bass.h:149
BassConfigIosNocategory = 51
// BassConfigVerifyNet as defined in include/bass.h:150
BassConfigVerifyNet = 52
// BassConfigDevPeriod as defined in include/bass.h:151
BassConfigDevPeriod = 53
// BassConfigFloat as defined in include/bass.h:152
BassConfigFloat = 54
// BassConfigNetSeek as defined in include/bass.h:153
BassConfigNetSeek = 56
// BassConfigAmDisable as defined in include/bass.h:154
BassConfigAmDisable = 58
// BassConfigNetPlaylistDepth as defined in include/bass.h:155
BassConfigNetPlaylistDepth = 59
// BassConfigNetPrebufWait as defined in include/bass.h:156
BassConfigNetPrebufWait = 60
// BassConfigAndroidSessionid as defined in include/bass.h:157
BassConfigAndroidSessionid = 62
// BassConfigWasapiPersist as defined in include/bass.h:158
BassConfigWasapiPersist = 65
// BassConfigRecWasapi as defined in include/bass.h:159
BassConfigRecWasapi = 66
// BassConfigAndroidAaudio as defined in include/bass.h:160
BassConfigAndroidAaudio = 67
// BassConfigSampleOnehandle as defined in include/bass.h:161
BassConfigSampleOnehandle = 69
// BassConfigNetMeta as defined in include/bass.h:162
BassConfigNetMeta = 71
// BassConfigNetRestrate as defined in include/bass.h:163
BassConfigNetRestrate = 72
// BassConfigRecDefault as defined in include/bass.h:164
BassConfigRecDefault = 73
// BassConfigNoramp as defined in include/bass.h:165
BassConfigNoramp = 74
// BassConfigNetAgent as defined in include/bass.h:168
BassConfigNetAgent = 16
// BassConfigNetProxy as defined in include/bass.h:169
BassConfigNetProxy = 17
// BassConfigIosNotify as defined in include/bass.h:170
BassConfigIosNotify = 46
// BassConfigAndroidJavavm as defined in include/bass.h:171
BassConfigAndroidJavavm = 63
// BassConfigLibssl as defined in include/bass.h:172
BassConfigLibssl = 64
// BassConfigFilename as defined in include/bass.h:173
BassConfigFilename = 75
// BassConfigThread as defined in include/bass.h:175
BassConfigThread = 0x40000000
// BassIosSessionMix as defined in include/bass.h:178
BassIosSessionMix = 1
// BassIosSessionDuck as defined in include/bass.h:179
BassIosSessionDuck = 2
// BassIosSessionAmbient as defined in include/bass.h:180
BassIosSessionAmbient = 4
// BassIosSessionSpeaker as defined in include/bass.h:181
BassIosSessionSpeaker = 8
// BassIosSessionDisable as defined in include/bass.h:182
BassIosSessionDisable = 16
// BassIosSessionDeactivate as defined in include/bass.h:183
BassIosSessionDeactivate = 32
// BassIosSessionAirplay as defined in include/bass.h:184
BassIosSessionAirplay = 64
// BassIosSessionBthfp as defined in include/bass.h:185
BassIosSessionBthfp = 128
// BassIosSessionBta2dp as defined in include/bass.h:186
BassIosSessionBta2dp = 0x100
// BassDevice8bits as defined in include/bass.h:189
BassDevice8bits = 1
// BassDeviceMono as defined in include/bass.h:190
BassDeviceMono = 2
// BassDevice3d as defined in include/bass.h:191
BassDevice3d = 4
// BassDevice16bits as defined in include/bass.h:192
BassDevice16bits = 8
// BassDeviceReinit as defined in include/bass.h:193
BassDeviceReinit = 128
// BassDeviceLatency as defined in include/bass.h:194
BassDeviceLatency = 0x100
// BassDeviceCpspeakers as defined in include/bass.h:195
BassDeviceCpspeakers = 0x400
// BassDeviceSpeakers as defined in include/bass.h:196
BassDeviceSpeakers = 0x800
// BassDeviceNospeaker as defined in include/bass.h:197
BassDeviceNospeaker = 0x1000
// BassDeviceDmix as defined in include/bass.h:198
BassDeviceDmix = 0x2000
// BassDeviceFreq as defined in include/bass.h:199
BassDeviceFreq = 0x4000
// BassDeviceStereo as defined in include/bass.h:200
BassDeviceStereo = 0x8000
// BassDeviceHog as defined in include/bass.h:201
BassDeviceHog = 0x10000
// BassDeviceAudiotrack as defined in include/bass.h:202
BassDeviceAudiotrack = 0x20000
// BassDeviceDsound as defined in include/bass.h:203
BassDeviceDsound = 0x40000
// BassDeviceSoftware as defined in include/bass.h:204
BassDeviceSoftware = 0x80000
// BassObjectDs as defined in include/bass.h:207
BassObjectDs = 1
// BassObjectDs3dl as defined in include/bass.h:208
BassObjectDs3dl = 2
// BassDeviceEnabled as defined in include/bass.h:223
BassDeviceEnabled = 1
// BassDeviceDefault as defined in include/bass.h:224
BassDeviceDefault = 2
// BassDeviceInit as defined in include/bass.h:225
BassDeviceInit = 4
// BassDeviceLoopback as defined in include/bass.h:226
BassDeviceLoopback = 8
// BassDeviceDefaultcom as defined in include/bass.h:227
BassDeviceDefaultcom = 128
// BassDeviceTypeMask as defined in include/bass.h:229
BassDeviceTypeMask = 0xff000000
// BassDeviceTypeNetwork as defined in include/bass.h:230
BassDeviceTypeNetwork = 0x01000000
// BassDeviceTypeSpeakers as defined in include/bass.h:231
BassDeviceTypeSpeakers = 0x02000000
// BassDeviceTypeLine as defined in include/bass.h:232
BassDeviceTypeLine = 0x03000000
// BassDeviceTypeHeadphones as defined in include/bass.h:233
BassDeviceTypeHeadphones = 0x04000000
// BassDeviceTypeMicrophone as defined in include/bass.h:234
BassDeviceTypeMicrophone = 0x05000000
// BassDeviceTypeHeadset as defined in include/bass.h:235
BassDeviceTypeHeadset = 0x06000000
// BassDeviceTypeHandset as defined in include/bass.h:236
BassDeviceTypeHandset = 0x07000000
// BassDeviceTypeDigital as defined in include/bass.h:237
BassDeviceTypeDigital = 0x08000000
// BassDeviceTypeSpdif as defined in include/bass.h:238
BassDeviceTypeSpdif = 0x09000000
// BassDeviceTypeHdmi as defined in include/bass.h:239
BassDeviceTypeHdmi = 0x0a000000
// BassDeviceTypeDisplayport as defined in include/bass.h:240
BassDeviceTypeDisplayport = 0x40000000
// BassDevicesAirplay as defined in include/bass.h:243
BassDevicesAirplay = 0x1000000
// BassSample8bits as defined in include/bass.h:318
BassSample8bits = 1
// BassSampleFloat as defined in include/bass.h:319
BassSampleFloat = 256
// BassSampleMono as defined in include/bass.h:320
BassSampleMono = 2
// BassSampleLoop as defined in include/bass.h:321
BassSampleLoop = 4
// BassSample3d as defined in include/bass.h:322
BassSample3d = 8
// BassSampleSoftware as defined in include/bass.h:323
BassSampleSoftware = 16
// BassSampleMutemax as defined in include/bass.h:324
BassSampleMutemax = 32
// BassSampleVam as defined in include/bass.h:325
BassSampleVam = 64
// BassSampleFx as defined in include/bass.h:326
BassSampleFx = 128
// BassSampleOverVol as defined in include/bass.h:327
BassSampleOverVol = 0x10000
// BassSampleOverPos as defined in include/bass.h:328
BassSampleOverPos = 0x20000
// BassSampleOverDist as defined in include/bass.h:329
BassSampleOverDist = 0x30000
// BassStreamPrescan as defined in include/bass.h:331
BassStreamPrescan = 0x20000
// BassStreamAutofree as defined in include/bass.h:332
BassStreamAutofree = 0x40000
// BassStreamRestrate as defined in include/bass.h:333
BassStreamRestrate = 0x80000
// BassStreamBlock as defined in include/bass.h:334
BassStreamBlock = 0x100000
// BassStreamDecode as defined in include/bass.h:335
BassStreamDecode = 0x200000
// BassStreamStatus as defined in include/bass.h:336
BassStreamStatus = 0x800000
// BassMp3Ignoredelay as defined in include/bass.h:338
BassMp3Ignoredelay = 0x200
// BassMp3Setpos as defined in include/bass.h:339
BassMp3Setpos = BassStreamPrescan
// BassMusicFloat as defined in include/bass.h:341
BassMusicFloat = BassSampleFloat
// BassMusicMono as defined in include/bass.h:342
BassMusicMono = BassSampleMono
// BassMusicLoop as defined in include/bass.h:343
BassMusicLoop = BassSampleLoop
// BassMusic3d as defined in include/bass.h:344
BassMusic3d = BassSample3d
// BassMusicFx as defined in include/bass.h:345
BassMusicFx = BassSampleFx
// BassMusicAutofree as defined in include/bass.h:346
BassMusicAutofree = BassStreamAutofree
// BassMusicDecode as defined in include/bass.h:347
BassMusicDecode = BassStreamDecode
// BassMusicPrescan as defined in include/bass.h:348
BassMusicPrescan = BassStreamPrescan
// BassMusicCalclen as defined in include/bass.h:349
BassMusicCalclen = BassMusicPrescan
// BassMusicRamp as defined in include/bass.h:350
BassMusicRamp = 0x200
// BassMusicRamps as defined in include/bass.h:351
BassMusicRamps = 0x400
// BassMusicSurround as defined in include/bass.h:352
BassMusicSurround = 0x800
// BassMusicSurround2 as defined in include/bass.h:353
BassMusicSurround2 = 0x1000
// BassMusicFt2pan as defined in include/bass.h:354
BassMusicFt2pan = 0x2000
// BassMusicFt2mod as defined in include/bass.h:355
BassMusicFt2mod = 0x2000
// BassMusicPt1mod as defined in include/bass.h:356
BassMusicPt1mod = 0x4000
// BassMusicNoninter as defined in include/bass.h:357
BassMusicNoninter = 0x10000
// BassMusicSincinter as defined in include/bass.h:358
BassMusicSincinter = 0x800000
// BassMusicPosreset as defined in include/bass.h:359
BassMusicPosreset = 0x8000
// BassMusicPosresetex as defined in include/bass.h:360
BassMusicPosresetex = 0x400000
// BassMusicStopback as defined in include/bass.h:361
BassMusicStopback = 0x80000
// BassMusicNosample as defined in include/bass.h:362
BassMusicNosample = 0x100000
// BassSpeakerFront as defined in include/bass.h:365
BassSpeakerFront = 0x1000000
// BassSpeakerRear as defined in include/bass.h:366
BassSpeakerRear = 0x2000000
// BassSpeakerCenlfe as defined in include/bass.h:367
BassSpeakerCenlfe = 0x3000000
// BassSpeakerSide as defined in include/bass.h:368
BassSpeakerSide = 0x4000000
// BassSpeakerLeft as defined in include/bass.h:370
BassSpeakerLeft = 0x10000000
// BassSpeakerRight as defined in include/bass.h:371
BassSpeakerRight = 0x20000000
// BassSpeakerFrontleft as defined in include/bass.h:372
BassSpeakerFrontleft = BassSpeakerFront | BassSpeakerLeft
// BassSpeakerFrontright as defined in include/bass.h:373
BassSpeakerFrontright = BassSpeakerFront | BassSpeakerRight
// BassSpeakerRearleft as defined in include/bass.h:374
BassSpeakerRearleft = BassSpeakerRear | BassSpeakerLeft
// BassSpeakerRearright as defined in include/bass.h:375
BassSpeakerRearright = BassSpeakerRear | BassSpeakerRight
// BassSpeakerCenter as defined in include/bass.h:376
BassSpeakerCenter = BassSpeakerCenlfe | BassSpeakerLeft
// BassSpeakerLfe as defined in include/bass.h:377
BassSpeakerLfe = BassSpeakerCenlfe | BassSpeakerRight
// BassSpeakerSideleft as defined in include/bass.h:378
BassSpeakerSideleft = BassSpeakerSide | BassSpeakerLeft
// BassSpeakerSideright as defined in include/bass.h:379
BassSpeakerSideright = BassSpeakerSide | BassSpeakerRight
// BassSpeakerRear2 as defined in include/bass.h:380
BassSpeakerRear2 = BassSpeakerSide
// BassSpeakerRear2left as defined in include/bass.h:381
BassSpeakerRear2left = BassSpeakerSideleft
// BassSpeakerRear2right as defined in include/bass.h:382
BassSpeakerRear2right = BassSpeakerSideright
// BassAsyncfile as defined in include/bass.h:384
BassAsyncfile = 0x40000000
// BassUnicode as defined in include/bass.h:385
BassUnicode = 0x80000000
// BassRecordEchocancel as defined in include/bass.h:387
BassRecordEchocancel = 0x2000
// BassRecordAgc as defined in include/bass.h:388
BassRecordAgc = 0x4000
// BassRecordPause as defined in include/bass.h:389
BassRecordPause = 0x8000
// BassVamHardware as defined in include/bass.h:392
BassVamHardware = 1
// BassVamSoftware as defined in include/bass.h:393
BassVamSoftware = 2
// BassVamTermTime as defined in include/bass.h:394
BassVamTermTime = 4
// BassVamTermDist as defined in include/bass.h:395
BassVamTermDist = 8
// BassVamTermPrio as defined in include/bass.h:396
BassVamTermPrio = 16
// BassOrigresFloat as defined in include/bass.h:410
BassOrigresFloat = 0x10000
// BassCtypeSample as defined in include/bass.h:413
BassCtypeSample = 1
// BassCtypeRecord as defined in include/bass.h:414
BassCtypeRecord = 2
// BassCtypeStream as defined in include/bass.h:415
BassCtypeStream = 0x10000
// BassCtypeStreamVorbis as defined in include/bass.h:416
BassCtypeStreamVorbis = 0x10002
// BassCtypeStreamOgg as defined in include/bass.h:417
BassCtypeStreamOgg = 0x10002
// BassCtypeStreamMp1 as defined in include/bass.h:418
BassCtypeStreamMp1 = 0x10003
// BassCtypeStreamMp2 as defined in include/bass.h:419
BassCtypeStreamMp2 = 0x10004
// BassCtypeStreamMp3 as defined in include/bass.h:420
BassCtypeStreamMp3 = 0x10005
// BassCtypeStreamAiff as defined in include/bass.h:421
BassCtypeStreamAiff = 0x10006
// BassCtypeStreamCa as defined in include/bass.h:422
BassCtypeStreamCa = 0x10007
// BassCtypeStreamMf as defined in include/bass.h:423
BassCtypeStreamMf = 0x10008
// BassCtypeStreamAm as defined in include/bass.h:424
BassCtypeStreamAm = 0x10009
// BassCtypeStreamSample as defined in include/bass.h:425
BassCtypeStreamSample = 0x1000a
// BassCtypeStreamDummy as defined in include/bass.h:426
BassCtypeStreamDummy = 0x18000
// BassCtypeStreamDevice as defined in include/bass.h:427
BassCtypeStreamDevice = 0x18001
// BassCtypeStreamWav as defined in include/bass.h:428
BassCtypeStreamWav = 0x40000
// BassCtypeStreamWavPcm as defined in include/bass.h:429
BassCtypeStreamWavPcm = 0x50001
// BassCtypeStreamWavFloat as defined in include/bass.h:430
BassCtypeStreamWavFloat = 0x50003
// BassCtypeMusicMod as defined in include/bass.h:431
BassCtypeMusicMod = 0x20000
// BassCtypeMusicMtm as defined in include/bass.h:432
BassCtypeMusicMtm = 0x20001
// BassCtypeMusicS3m as defined in include/bass.h:433
BassCtypeMusicS3m = 0x20002
// BassCtypeMusicXm as defined in include/bass.h:434
BassCtypeMusicXm = 0x20003
// BassCtypeMusicIt as defined in include/bass.h:435
BassCtypeMusicIt = 0x20004
// BassCtypeMusicMo3 as defined in include/bass.h:436
BassCtypeMusicMo3 = 0x00100
// BassPluginProc as defined in include/bass.h:439
BassPluginProc = 1
// Bass3dmodeNormal as defined in include/bass.h:470
Bass3dmodeNormal = 0
// Bass3dmodeRelative as defined in include/bass.h:471
Bass3dmodeRelative = 1
// Bass3dmodeOff as defined in include/bass.h:472
Bass3dmodeOff = 2
// Bass3dalgDefault as defined in include/bass.h:475
Bass3dalgDefault = 0
// Bass3dalgOff as defined in include/bass.h:476
Bass3dalgOff = 1
// Bass3dalgFull as defined in include/bass.h:477
Bass3dalgFull = 2
// Bass3dalgLight as defined in include/bass.h:478
Bass3dalgLight = 3
// BassSamchanNew as defined in include/bass.h:481
BassSamchanNew = 1
// BassSamchanStream as defined in include/bass.h:482
BassSamchanStream = 2
// BassStreamprocEnd as defined in include/bass.h:492
BassStreamprocEnd = 0x80000000
// StreamprocDummy as defined in include/bass.h:495
StreamprocDummy = 0
// StreamprocPush as defined in include/bass.h:496
StreamprocPush = -1
// StreamprocDevice as defined in include/bass.h:497
StreamprocDevice = -2
// StreamprocDevice3d as defined in include/bass.h:498
StreamprocDevice3d = -3
// StreamfileNobuffer as defined in include/bass.h:501
StreamfileNobuffer = 0
// StreamfileBuffer as defined in include/bass.h:502
StreamfileBuffer = 1
// StreamfileBufferpush as defined in include/bass.h:503
StreamfileBufferpush = 2
// BassFiledataEnd as defined in include/bass.h:519
BassFiledataEnd = 0
// BassFileposCurrent as defined in include/bass.h:522
BassFileposCurrent = 0
// BassFileposDecode as defined in include/bass.h:523
BassFileposDecode = BassFileposCurrent
// BassFileposDownload as defined in include/bass.h:524
BassFileposDownload = 1
// BassFileposEnd as defined in include/bass.h:525
BassFileposEnd = 2
// BassFileposStart as defined in include/bass.h:526
BassFileposStart = 3
// BassFileposConnected as defined in include/bass.h:527
BassFileposConnected = 4
// BassFileposBuffer as defined in include/bass.h:528
BassFileposBuffer = 5
// BassFileposSocket as defined in include/bass.h:529
BassFileposSocket = 6
// BassFileposAsyncbuf as defined in include/bass.h:530
BassFileposAsyncbuf = 7
// BassFileposSize as defined in include/bass.h:531
BassFileposSize = 8
// BassFileposBuffering as defined in include/bass.h:532
BassFileposBuffering = 9
// BassFileposAvailable as defined in include/bass.h:533
BassFileposAvailable = 10
// BassSyncPos as defined in include/bass.h:542
BassSyncPos = 0
// BassSyncEnd as defined in include/bass.h:543
BassSyncEnd = 2
// BassSyncMeta as defined in include/bass.h:544
BassSyncMeta = 4
// BassSyncSlide as defined in include/bass.h:545
BassSyncSlide = 5
// BassSyncStall as defined in include/bass.h:546
BassSyncStall = 6
// BassSyncDownload as defined in include/bass.h:547
BassSyncDownload = 7
// BassSyncFree as defined in include/bass.h:548
BassSyncFree = 8
// BassSyncSetpos as defined in include/bass.h:549
BassSyncSetpos = 11
// BassSyncMusicpos as defined in include/bass.h:550
BassSyncMusicpos = 10
// BassSyncMusicinst as defined in include/bass.h:551
BassSyncMusicinst = 1
// BassSyncMusicfx as defined in include/bass.h:552
BassSyncMusicfx = 3
// BassSyncOggChange as defined in include/bass.h:553
BassSyncOggChange = 12
// BassSyncDevFail as defined in include/bass.h:554
BassSyncDevFail = 14
// BassSyncDevFormat as defined in include/bass.h:555
BassSyncDevFormat = 15
// BassSyncThread as defined in include/bass.h:556
BassSyncThread = 0x20000000
// BassSyncMixtime as defined in include/bass.h:557
BassSyncMixtime = 0x40000000
// BassSyncOnetime as defined in include/bass.h:558
BassSyncOnetime = 0x80000000
// BassActiveStopped as defined in include/bass.h:584
BassActiveStopped = 0
// BassActivePlaying as defined in include/bass.h:585
BassActivePlaying = 1
// BassActiveStalled as defined in include/bass.h:586
BassActiveStalled = 2
// BassActivePaused as defined in include/bass.h:587
BassActivePaused = 3
// BassActivePausedDevice as defined in include/bass.h:588
BassActivePausedDevice = 4
// BassAttribFreq as defined in include/bass.h:591
BassAttribFreq = 1
// BassAttribVol as defined in include/bass.h:592
BassAttribVol = 2
// BassAttribPan as defined in include/bass.h:593
BassAttribPan = 3
// BassAttribEaxmix as defined in include/bass.h:594
BassAttribEaxmix = 4
// BassAttribNobuffer as defined in include/bass.h:595
BassAttribNobuffer = 5
// BassAttribVbr as defined in include/bass.h:596
BassAttribVbr = 6
// BassAttribCpu as defined in include/bass.h:597
BassAttribCpu = 7
// BassAttribSrc as defined in include/bass.h:598
BassAttribSrc = 8
// BassAttribNetResume as defined in include/bass.h:599
BassAttribNetResume = 9
// BassAttribScaninfo as defined in include/bass.h:600
BassAttribScaninfo = 10
// BassAttribNoramp as defined in include/bass.h:601
BassAttribNoramp = 11
// BassAttribBitrate as defined in include/bass.h:602
BassAttribBitrate = 12
// BassAttribBuffer as defined in include/bass.h:603
BassAttribBuffer = 13
// BassAttribGranule as defined in include/bass.h:604
BassAttribGranule = 14
// BassAttribUser as defined in include/bass.h:605
BassAttribUser = 15
// BassAttribTail as defined in include/bass.h:606
BassAttribTail = 16
// BassAttribPushLimit as defined in include/bass.h:607
BassAttribPushLimit = 17
// BassAttribDownloadproc as defined in include/bass.h:608
BassAttribDownloadproc = 18
// BassAttribVoldsp as defined in include/bass.h:609
BassAttribVoldsp = 19
// BassAttribVoldspPriority as defined in include/bass.h:610
BassAttribVoldspPriority = 20
// BassAttribMusicAmplify as defined in include/bass.h:611
BassAttribMusicAmplify = 0x100
// BassAttribMusicPansep as defined in include/bass.h:612
BassAttribMusicPansep = 0x101
// BassAttribMusicPscaler as defined in include/bass.h:613
BassAttribMusicPscaler = 0x102
// BassAttribMusicBpm as defined in include/bass.h:614
BassAttribMusicBpm = 0x103
// BassAttribMusicSpeed as defined in include/bass.h:615
BassAttribMusicSpeed = 0x104
// BassAttribMusicVolGlobal as defined in include/bass.h:616
BassAttribMusicVolGlobal = 0x105
// BassAttribMusicActive as defined in include/bass.h:617
BassAttribMusicActive = 0x106
// BassAttribMusicVolChan as defined in include/bass.h:618
BassAttribMusicVolChan = 0x200
// BassAttribMusicVolInst as defined in include/bass.h:619
BassAttribMusicVolInst = 0x300
// BassSlideLog as defined in include/bass.h:622
BassSlideLog = 0x1000000
// BassDataAvailable as defined in include/bass.h:625
BassDataAvailable = 0
// BassDataNoremove as defined in include/bass.h:626
BassDataNoremove = 0x10000000
// BassDataFixed as defined in include/bass.h:627
BassDataFixed = 0x20000000
// BassDataFloat as defined in include/bass.h:628
BassDataFloat = 0x40000000
// BassDataFft256 as defined in include/bass.h:629
BassDataFft256 = 0x80000000
// BassDataFft512 as defined in include/bass.h:630
BassDataFft512 = 0x80000001
// BassDataFft1024 as defined in include/bass.h:631
BassDataFft1024 = 0x80000002
// BassDataFft2048 as defined in include/bass.h:632
BassDataFft2048 = 0x80000003
// BassDataFft4096 as defined in include/bass.h:633
BassDataFft4096 = 0x80000004
// BassDataFft8192 as defined in include/bass.h:634
BassDataFft8192 = 0x80000005
// BassDataFft16384 as defined in include/bass.h:635
BassDataFft16384 = 0x80000006
// BassDataFft32768 as defined in include/bass.h:636
BassDataFft32768 = 0x80000007
// BassDataFftIndividual as defined in include/bass.h:637
BassDataFftIndividual = 0x10
// BassDataFftNowindow as defined in include/bass.h:638
BassDataFftNowindow = 0x20
// BassDataFftRemovedc as defined in include/bass.h:639
BassDataFftRemovedc = 0x40
// BassDataFftComplex as defined in include/bass.h:640
BassDataFftComplex = 0x80
// BassDataFftNyquist as defined in include/bass.h:641
BassDataFftNyquist = 0x100
// BassLevelMono as defined in include/bass.h:644
BassLevelMono = 1
// BassLevelStereo as defined in include/bass.h:645
BassLevelStereo = 2
// BassLevelRms as defined in include/bass.h:646
BassLevelRms = 4
// BassLevelVolpan as defined in include/bass.h:647
BassLevelVolpan = 8
// BassLevelNoremove as defined in include/bass.h:648
BassLevelNoremove = 16
// BassTagId3 as defined in include/bass.h:651
BassTagId3 = 0
// BassTagId3v2 as defined in include/bass.h:652
BassTagId3v2 = 1
// BassTagOgg as defined in include/bass.h:653
BassTagOgg = 2
// BassTagHttp as defined in include/bass.h:654
BassTagHttp = 3
// BassTagIcy as defined in include/bass.h:655
BassTagIcy = 4
// BassTagMeta as defined in include/bass.h:656
BassTagMeta = 5
// BassTagApe as defined in include/bass.h:657
BassTagApe = 6
// BassTagMp4 as defined in include/bass.h:658
BassTagMp4 = 7
// BassTagWma as defined in include/bass.h:659
BassTagWma = 8
// BassTagVendor as defined in include/bass.h:660
BassTagVendor = 9
// BassTagLyrics3 as defined in include/bass.h:661
BassTagLyrics3 = 10
// BassTagCaCodec as defined in include/bass.h:662
BassTagCaCodec = 11
// BassTagMf as defined in include/bass.h:663
BassTagMf = 13
// BassTagWaveformat as defined in include/bass.h:664
BassTagWaveformat = 14
// BassTagAmName as defined in include/bass.h:665
BassTagAmName = 16
// BassTagId3v22 as defined in include/bass.h:666
BassTagId3v22 = 17
// BassTagAmMime as defined in include/bass.h:667
BassTagAmMime = 18
// BassTagLocation as defined in include/bass.h:668
BassTagLocation = 19
// BassTagRiffInfo as defined in include/bass.h:669
BassTagRiffInfo = 0x100
// BassTagRiffBext as defined in include/bass.h:670
BassTagRiffBext = 0x101
// BassTagRiffCart as defined in include/bass.h:671
BassTagRiffCart = 0x102
// BassTagRiffDisp as defined in include/bass.h:672
BassTagRiffDisp = 0x103
// BassTagRiffCue as defined in include/bass.h:673
BassTagRiffCue = 0x104
// BassTagRiffSmpl as defined in include/bass.h:674
BassTagRiffSmpl = 0x105
// BassTagApeBinary as defined in include/bass.h:675
BassTagApeBinary = 0x1000
// BassTagMusicName as defined in include/bass.h:676
BassTagMusicName = 0x10000
// BassTagMusicMessage as defined in include/bass.h:677
BassTagMusicMessage = 0x10001
// BassTagMusicOrders as defined in include/bass.h:678
BassTagMusicOrders = 0x10002
// BassTagMusicAuth as defined in include/bass.h:679
BassTagMusicAuth = 0x10003
// BassTagMusicInst as defined in include/bass.h:680
BassTagMusicInst = 0x10100
// BassTagMusicChan as defined in include/bass.h:681
BassTagMusicChan = 0x10200
// BassTagMusicSample as defined in include/bass.h:682
BassTagMusicSample = 0x10300
// BassPosByte as defined in include/bass.h:847
BassPosByte = 0
// BassPosMusicOrder as defined in include/bass.h:848
BassPosMusicOrder = 1
// BassPosOgg as defined in include/bass.h:849
BassPosOgg = 3
// BassPosEnd as defined in include/bass.h:850
BassPosEnd = 0x10
// BassPosLoop as defined in include/bass.h:851
BassPosLoop = 0x11
// BassPosFlush as defined in include/bass.h:852
BassPosFlush = 0x1000000
// BassPosReset as defined in include/bass.h:853
BassPosReset = 0x2000000
// BassPosRelative as defined in include/bass.h:854
BassPosRelative = 0x4000000
// BassPosInexact as defined in include/bass.h:855
BassPosInexact = 0x8000000
// BassPosDecode as defined in include/bass.h:856
BassPosDecode = 0x10000000
// BassPosDecodeto as defined in include/bass.h:857
BassPosDecodeto = 0x20000000
// BassPosScan as defined in include/bass.h:858
BassPosScan = 0x40000000
// BassNodevice as defined in include/bass.h:861
BassNodevice = 0x20000
// BassInputOff as defined in include/bass.h:864
BassInputOff = 0x10000
// BassInputOn as defined in include/bass.h:865
BassInputOn = 0x20000
// BassInputTypeMask as defined in include/bass.h:867
BassInputTypeMask = 0xff000000
// BassInputTypeUndef as defined in include/bass.h:868
BassInputTypeUndef = 0x00000000
// BassInputTypeDigital as defined in include/bass.h:869
BassInputTypeDigital = 0x01000000
// BassInputTypeLine as defined in include/bass.h:870
BassInputTypeLine = 0x02000000
// BassInputTypeMic as defined in include/bass.h:871
BassInputTypeMic = 0x03000000
// BassInputTypeSynth as defined in include/bass.h:872
BassInputTypeSynth = 0x04000000
// BassInputTypeCd as defined in include/bass.h:873
BassInputTypeCd = 0x05000000
// BassInputTypePhone as defined in include/bass.h:874
BassInputTypePhone = 0x06000000
// BassInputTypeSpeaker as defined in include/bass.h:875
BassInputTypeSpeaker = 0x07000000
// BassInputTypeWave as defined in include/bass.h:876
BassInputTypeWave = 0x08000000
// BassInputTypeAux as defined in include/bass.h:877
BassInputTypeAux = 0x09000000
// BassInputTypeAnalog as defined in include/bass.h:878
BassInputTypeAnalog = 0x0a000000
// BassFxDx8Chorus as defined in include/bass.h:881
BassFxDx8Chorus = 0
// BassFxDx8Compressor as defined in include/bass.h:882
BassFxDx8Compressor = 1
// BassFxDx8Distortion as defined in include/bass.h:883
BassFxDx8Distortion = 2
// BassFxDx8Echo as defined in include/bass.h:884
BassFxDx8Echo = 3
// BassFxDx8Flanger as defined in include/bass.h:885
BassFxDx8Flanger = 4
// BassFxDx8Gargle as defined in include/bass.h:886
BassFxDx8Gargle = 5
// BassFxDx8I3dl2reverb as defined in include/bass.h:887
BassFxDx8I3dl2reverb = 6
// BassFxDx8Parameq as defined in include/bass.h:888
BassFxDx8Parameq = 7
// BassFxDx8Reverb as defined in include/bass.h:889
BassFxDx8Reverb = 8
// BassFxVolume as defined in include/bass.h:890
BassFxVolume = 9
// BassDx8PhaseNeg180 as defined in include/bass.h:970
BassDx8PhaseNeg180 = 0
// BassDx8PhaseNeg90 as defined in include/bass.h:971
BassDx8PhaseNeg90 = 1
// BassDx8PhaseZero as defined in include/bass.h:972
BassDx8PhaseZero = 2
// BassDx8Phase90 as defined in include/bass.h:973
BassDx8Phase90 = 3
// BassDx8Phase180 as defined in include/bass.h:974
BassDx8Phase180 = 4
// BassIosnotifyInterrupt as defined in include/bass.h:987
BassIosnotifyInterrupt = 1
// BassIosnotifyInterruptEnd as defined in include/bass.h:988
BassIosnotifyInterruptEnd = 2

// BassencH as defined in include/bassenc.h:9

// BassErrorAcmCancel as defined in include/bassenc.h:33
BassErrorAcmCancel = 2000
// BassErrorCastDenied as defined in include/bassenc.h:34
BassErrorCastDenied = 2100
// BassErrorServerCert as defined in include/bassenc.h:35
BassErrorServerCert = 2101
// BassConfigEncodePriority as defined in include/bassenc.h:38
BassConfigEncodePriority = 0x10300
// BassConfigEncodeQueue as defined in include/bassenc.h:39
BassConfigEncodeQueue = 0x10301
// BassConfigEncodeCastTimeout as defined in include/bassenc.h:40
BassConfigEncodeCastTimeout = 0x10310
// BassConfigEncodeAcmLoad as defined in include/bassenc.h:43
BassConfigEncodeAcmLoad = 0x10302
// BassConfigEncodeCastProxy as defined in include/bassenc.h:44
BassConfigEncodeCastProxy = 0x10311
// BassConfigEncodeCastBind as defined in include/bassenc.h:45
BassConfigEncodeCastBind = 0x10312
// BassConfigEncodeServerCert as defined in include/bassenc.h:46
BassConfigEncodeServerCert = 0x10320
// BassConfigEncodeServerKey as defined in include/bassenc.h:47
BassConfigEncodeServerKey = 0x10321
// BassEncodeNohead as defined in include/bassenc.h:50
BassEncodeNohead = 1
// BassEncodeFp8bit as defined in include/bassenc.h:51
BassEncodeFp8bit = 2
// BassEncodeFp16bit as defined in include/bassenc.h:52
BassEncodeFp16bit = 4
// BassEncodeFp24bit as defined in include/bassenc.h:53
BassEncodeFp24bit = 6
// BassEncodeFp32bit as defined in include/bassenc.h:54
BassEncodeFp32bit = 8
// BassEncodeFpAuto as defined in include/bassenc.h:55
BassEncodeFpAuto = 14
// BassEncodeBigend as defined in include/bassenc.h:56
BassEncodeBigend = 16
// BassEncodePause as defined in include/bassenc.h:57
BassEncodePause = 32
// BassEncodePcm as defined in include/bassenc.h:58
BassEncodePcm = 64
// BassEncodeRf64 as defined in include/bassenc.h:59
BassEncodeRf64 = 128
// BassEncodeMono as defined in include/bassenc.h:60
BassEncodeMono = 0x100
// BassEncodeQueue as defined in include/bassenc.h:61
BassEncodeQueue = 0x200
// BassEncodeWfext as defined in include/bassenc.h:62
BassEncodeWfext = 0x400
// BassEncodeCastNolimit as defined in include/bassenc.h:63
BassEncodeCastNolimit = 0x1000
// BassEncodeLimit as defined in include/bassenc.h:64
BassEncodeLimit = 0x2000
// BassEncodeAiff as defined in include/bassenc.h:65
BassEncodeAiff = 0x4000
// BassEncodeDither as defined in include/bassenc.h:66
BassEncodeDither = 0x8000
// BassEncodeAutofree as defined in include/bassenc.h:67
BassEncodeAutofree = 0x40000
// BassAcmDefault as defined in include/bassenc.h:70
BassAcmDefault = 1
// BassAcmRate as defined in include/bassenc.h:71
BassAcmRate = 2
// BassAcmChans as defined in include/bassenc.h:72
BassAcmChans = 4
// BassAcmSuggest as defined in include/bassenc.h:73
BassAcmSuggest = 8
// BassEncodeCountIn as defined in include/bassenc.h:76
BassEncodeCountIn = 0
// BassEncodeCountOut as defined in include/bassenc.h:77
BassEncodeCountOut = 1
// BassEncodeCountCast as defined in include/bassenc.h:78
BassEncodeCountCast = 2
// BassEncodeCountQueue as defined in include/bassenc.h:79
BassEncodeCountQueue = 3
// BassEncodeCountQueueLimit as defined in include/bassenc.h:80
BassEncodeCountQueueLimit = 4
// BassEncodeCountQueueFail as defined in include/bassenc.h:81
BassEncodeCountQueueFail = 5
// BassEncodeCountInFp as defined in include/bassenc.h:82
BassEncodeCountInFp = 6
// BassEncodeTypeMp3 as defined in include/bassenc.h:85
BassEncodeTypeMp3 = "audio/mpeg"
// BassEncodeTypeOgg as defined in include/bassenc.h:86
BassEncodeTypeOgg = "audio/ogg"
// BassEncodeTypeAac as defined in include/bassenc.h:87
BassEncodeTypeAac = "audio/aacp"
// BassEncodeCastPublic as defined in include/bassenc.h:90
BassEncodeCastPublic = 1
// BassEncodeCastPut as defined in include/bassenc.h:91
BassEncodeCastPut = 2
// BassEncodeCastSsl as defined in include/bassenc.h:92
BassEncodeCastSsl = 4
// BassEncodeStatsShout as defined in include/bassenc.h:95
BassEncodeStatsShout = 0
// BassEncodeStatsIce as defined in include/bassenc.h:96
BassEncodeStatsIce = 1
// BassEncodeStatsIceserv as defined in include/bassenc.h:97
BassEncodeStatsIceserv = 2
// BassEncodeServerNohttp as defined in include/bassenc.h:100
BassEncodeServerNohttp = 1
// BassEncodeServerMeta as defined in include/bassenc.h:101
BassEncodeServerMeta = 2
// BassEncodeServerSsl as defined in include/bassenc.h:102
BassEncodeServerSsl = 4
// BassEncodeServerSslonly as defined in include/bassenc.h:103
BassEncodeServerSslonly = 8
// BassEncodeNotifyEncoder as defined in include/bassenc.h:148
BassEncodeNotifyEncoder = 1
// BassEncodeNotifyCast as defined in include/bassenc.h:149
BassEncodeNotifyCast = 2
// BassEncodeNotifyServer as defined in include/bassenc.h:150
BassEncodeNotifyServer = 3
// BassEncodeNotifyCastTimeout as defined in include/bassenc.h:151
BassEncodeNotifyCastTimeout = 0x10000
// BassEncodeNotifyQueueFull as defined in include/bassenc.h:152
BassEncodeNotifyQueueFull = 0x10001
// BassEncodeNotifyFree as defined in include/bassenc.h:153
BassEncodeNotifyFree = 0x10002
// BassencAacH as defined in include/bassenc_aac.h:9

// BassencFlacH as defined in include/bassenc_flac.h:9

// BassEncodeFlacReset as defined in include/bassenc_flac.h:26
BassEncodeFlacReset = 0x1000000
// BassencMp3H as defined in include/bassenc_mp3.h:9

// BassencOggH as defined in include/bassenc_ogg.h:9

// BassEncodeOggReset as defined in include/bassenc_ogg.h:26
BassEncodeOggReset = 0x1000000
// BassmixH as defined in include/bassmix.h:9

// BassConfigMixerBuffer as defined in include/bassmix.h:31
BassConfigMixerBuffer = 0x10601
// BassConfigMixerPosex as defined in include/bassmix.h:32
BassConfigMixerPosex = 0x10602
// BassConfigSplitBuffer as defined in include/bassmix.h:33
BassConfigSplitBuffer = 0x10610
// BassMixerResume as defined in include/bassmix.h:36
BassMixerResume = 0x1000
// BassMixerPosex as defined in include/bassmix.h:37
BassMixerPosex = 0x2000
// BassMixerNospeaker as defined in include/bassmix.h:38
BassMixerNospeaker = 0x4000
// BassMixerQueue as defined in include/bassmix.h:39
BassMixerQueue = 0x8000
// BassMixerEnd as defined in include/bassmix.h:40
BassMixerEnd = 0x10000
// BassMixerNonstop as defined in include/bassmix.h:41
BassMixerNonstop = 0x20000
// BassMixerChanAbsolute as defined in include/bassmix.h:44
BassMixerChanAbsolute = 0x1000
// BassMixerChanBuffer as defined in include/bassmix.h:45
BassMixerChanBuffer = 0x2000
// BassMixerChanLimit as defined in include/bassmix.h:46
BassMixerChanLimit = 0x4000
// BassMixerChanMatrix as defined in include/bassmix.h:47
BassMixerChanMatrix = 0x10000
// BassMixerChanPause as defined in include/bassmix.h:48
BassMixerChanPause = 0x20000
// BassMixerChanDownmix as defined in include/bassmix.h:49
BassMixerChanDownmix = 0x400000
// BassMixerChanNorampin as defined in include/bassmix.h:50
BassMixerChanNorampin = 0x800000
// BassMixerBuffer as defined in include/bassmix.h:51
BassMixerBuffer = BassMixerChanBuffer
// BassMixerLimit as defined in include/bassmix.h:52
BassMixerLimit = BassMixerChanLimit
// BassMixerMatrix as defined in include/bassmix.h:53
BassMixerMatrix = BassMixerChanMatrix
// BassMixerPause as defined in include/bassmix.h:54
BassMixerPause = BassMixerChanPause
// BassMixerDownmix as defined in include/bassmix.h:55
BassMixerDownmix = BassMixerChanDownmix
// BassMixerNorampin as defined in include/bassmix.h:56
BassMixerNorampin = BassMixerChanNorampin
// BassAttribMixerLatency as defined in include/bassmix.h:59
BassAttribMixerLatency = 0x15000
// BassAttribMixerThreads as defined in include/bassmix.h:60
BassAttribMixerThreads = 0x15001
// BassAttribMixerVol as defined in include/bassmix.h:61
BassAttribMixerVol = 0x15002
// BassActiveWaiting as defined in include/bassmix.h:64
BassActiveWaiting = 5
// BassActiveQueued as defined in include/bassmix.h:65
BassActiveQueued = 6
// BassSplitSlave as defined in include/bassmix.h:68
BassSplitSlave = 0x1000
// BassSplitPos as defined in include/bassmix.h:69
BassSplitPos = 0x2000
// BassAttribSplitAsyncbuffer as defined in include/bassmix.h:72
BassAttribSplitAsyncbuffer = 0x15010
// BassAttribSplitAsyncperiod as defined in include/bassmix.h:73
BassAttribSplitAsyncperiod = 0x15011
// BassMixerEnvFreq as defined in include/bassmix.h:82
BassMixerEnvFreq = 1
// BassMixerEnvVol as defined in include/bassmix.h:83
BassMixerEnvVol = 2
// BassMixerEnvPan as defined in include/bassmix.h:84
BassMixerEnvPan = 3
// BassMixerEnvLoop as defined in include/bassmix.h:85
BassMixerEnvLoop = 0x10000
// BassMixerEnvRemove as defined in include/bassmix.h:86
BassMixerEnvRemove = 0x20000
// BassSyncMixerEnvelope as defined in include/bassmix.h:89
BassSyncMixerEnvelope = 0x10200
// BassSyncMixerEnvelopeNode as defined in include/bassmix.h:90
BassSyncMixerEnvelopeNode = 0x10201
// BassSyncMixerQueue as defined in include/bassmix.h:91
BassSyncMixerQueue = 0x10202
// BassPosMixerReset as defined in include/bassmix.h:94
BassPosMixerReset = 0x10000
// BassPosMixerDelay as defined in include/bassmix.h:97
BassPosMixerDelay = 5
// BassCtypeStreamMixer as defined in include/bassmix.h:100
BassCtypeStreamMixer = 0x10800
// BassCtypeStreamSplit as defined in include/bassmix.h:101
BassCtypeStreamSplit = 0x10801
)

