// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 30 Aug 2023 09:21:44 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
This package provides Go bindings for BASS.dll
*/
package bass
