// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 28 Jul 2022 15:21:50 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
This package provides Go bindings for BASS.dll
*/
package bass
