// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 11 Jun 2022 23:23:46 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
This package provides Go bindings for BASS.dll
*/
package bass
